version: '3'

services:
  app:
    build:
      context: ./
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - app_db:/var/lib/mysql

  proxy:
    image: nginx
    volumes:
      - ./node.conf:/etc/nginx/conf.d/default.conf
      - ./www/landing:/usr/share/nginx/landing
    ports:
      - 81:80

volumes:
  app_db:
